### PR TITLE
Add a convenient MultiExiftool.clear method to remove all metadata

### PR DESCRIPTION
**Pull request by szTheory**

### CODE REVIEW

**Comment by janfri** [comment]
I like the idea of MultiExiftool.clear but I have a more flexible solution in mind. Be patient. ;-)

**Comment by janfri** [comment]
I have added a new method ```MultiExiftool.delete_values``` with the possibility to delete values for all or some tags. See commit [c4297244](https://github.com/janfri/multi_exiftool/commit/c4297244c05783f8ea54ed222bb0e7e168e54eaf). Does this meet your requirements?

**Comment by szTheory** [comment]
Looks good!

**Comment by janfri** [comment]
Just released multi_exiftool version 0.9.0 which includes ```MultiExiftool.delete_values```. So I close the pull request.

**Pull request closed without merging**
